### PR TITLE
Finally the tribal smoke grenade

### PR DESCRIPTION
**Pull request by SerinaCE**
## Additions

Describe new functionality added by your code, e.g.
- Tribal smoke bombs
- New tribal smoke bomb sprite
- Tribal smoke bomb recipes at smithing bench and crafting spot using prometheum

### CODE REVIEW

**Comment by SamaelGray** [comment]
It's missing the README file entry.

**Comment by SerinaCE** [comment]
@N7Huntsman can we please merge this already? we can get the smoke pusher change on the base smoke grenade any time after.

**Comment by SerinaCE** [comment]
fuck's sake...

**Comment by SerinaCE** [comment]
fuck's sake...

**Pull request closed without merging**
